default_platform(:ios)

platform :ios do

  desc "Build app"
  lane :build_app do
    gym(
      scheme: "GithubActionCache",
      silent: true,
      suppress_xcode_output: true,
      skip_package_ipa: true,
      skip_codesigning: true,
      derived_data_path: './DerivedData',
      build_path: './Build',
      buildlog_path: './logs'
    )
  end

end
